# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUsers():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_users(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("test.users@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.LINK_TEXT, "Sign Up").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("test.users@gmail.com")
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("test users")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("12345678")
    self.driver.find_element(By.ID, "confirm_password").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("1234567890")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("12345678")
    self.driver.find_element(By.ID, "confirm_password").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("test.users@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "date_of_birth").click()
    self.driver.find_element(By.ID, "date_of_birth").send_keys("2023-05-26")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.ID, "date_of_birth").click()
    self.driver.find_element(By.ID, "date_of_birth").send_keys("2023-05-18")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Test Users")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.LINK_TEXT, "Forgot Password?").click()
    self.driver.find_element(By.ID, "email").send_keys("test.users@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.LINK_TEXT, "Sign Up").click()
    self.driver.find_element(By.ID, "email").send_keys("test.users@gmail.com")
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("test users")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("12345678")
    self.driver.find_element(By.ID, "confirm_password").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.LINK_TEXT, "login page").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hero-body").click()
  
