# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestComments():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_comments(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.find_element(By.LINK_TEXT, "Sign Up").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("test.comments@gmail.com")
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("test comments")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("12345678")
    self.driver.find_element(By.ID, "confirm_password").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.ID, "email").send_keys("test.comments@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.LINK_TEXT, "Create New Post").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("test comment title")
    self.driver.find_element(By.ID, "content").click()
    self.driver.find_element(By.ID, "content").send_keys("test comment content")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.LINK_TEXT, "test comment title").click()
    self.driver.find_element(By.CSS_SELECTOR, "form #content").click()
    self.driver.find_element(By.CSS_SELECTOR, "form #content").send_keys("test comment comment")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
